### ISSUE TITLE
Better error handling on saving Az modules

### ISSUE THREAD

**Issue by glennamanns** [Azure/azure-functions-powershell-worker#218]
I just received a CRI (119457109) from a customer whose application went down due to the following error:
_Exception: Fail to install function app dependencies. Restarting the app may resolve the error. Error: 'The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Unable to save the module 'Az'.'_

Restarting 5 times fixed the error. Ideally, our response to them is not for them to manually restart their application. Perhaps we should implement some retry logic that better handles module download failures.

**Comment by SatishRanjan** [comment]
Assigning this to @Francisco-Gamino for adding retry when downloading and saving Az modules, currently the workaround is to restart the function app.

**Comment by joeyaiello** [comment]
Retry could succeed if it's a network problem, but ideally we should figure out root cause of the failure so it doesn't happen. A single download takes long enough as it is, 5 will be a little crazy.

**Comment by Francisco-Gamino** [comment]
This issue has been addressed in PR #230.

**Comment by eosfor** [comment]
This is still an issue looks like

![Image](https://github.com/user-attachments/assets/047aaf42-ad98-45bf-accd-757633893af3)

```pwsh
# This file enables modules to be automatically managed by the Functions service.
# See https://aka.ms/functionsmanageddependency for additional information.
#
@{
    # For latest supported version, go to 'https://www.powershellgallery.com/packages/Az'. Uncomment the next line and replace the MAJOR_VERSION, e.g., 'Az' = '5.*'
    'Az' = '12.*';
    'AzTable' = '2.*'
}
```
